# Generated by Django 3.2 on 2023-11-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0002_auto_20231108_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='location',
        ),
    ]
