# Generated by Django 3.2 on 2023-11-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0003_remove_propertylisting_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertylisting',
            old_name='purchase_price',
            new_name='selling_price',
        ),
    ]
