# Generated by Django 3.2 on 2023-11-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='communication',
        ),
    ]
