# Generated by Django 3.2 on 2023-11-30 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tenant', '0002_remove_tenant_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Authorization.customuser'),
            preserve_default=False,
        ),
    ]
