# Generated by Django 3.2 on 2023-12-10 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0003_tenant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='payment_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenant.payment'),
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
