# Generated by Django 3.2 on 2023-11-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chat', '0001_initial'),
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('properties', models.ManyToManyField(to='Property.Property')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='ClientLandlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=255)),
                ('real_time_counter', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('communications', models.ManyToManyField(to='Chat.Communication')),
                ('property_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landlord.propertyportfolio')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
