PROPERTY_TYPE_CHOICES = [
    ("Apartment", "Apartment"),
    ("House", "House"),
    ("Commercial", "Commercial"),
    ("Bungalow", "Bungalow"),
    ("Duplex", "Duplex"),
    ("Mansion", "Mansion"),
    ("Terrace", "Terrace"),
    ("Penthouse", "Penthouse"),
    ("Land", "Land"),
]

DOCUMENT_TYPE_CHOICES = [
    ("Tenancy Agreement", "Tenancy Agreement"),
    ("Inspection Report", "Inspection Report"),
    ("Other", "Other"),
]

STATES_CHOICES = [
    ('Abuja', 'Federal Capital Territory'),
    ('Abia', 'Abia'),
    ('Adamawa', 'Adamawa'),
    ('Akwa Ibom', 'Akwa Ibom'),
    ('Anambra', 'Anambra'),
    ('Bauchi', 'Bauchi'),
    ('Bayelsa', 'Bayelsa'),
    ('Benue', 'Benue'),
    ('Borno', 'Borno'),
    ('Cross River', 'Cross River'),
    ('Delta', 'Delta'),
    ('Ebonyi', 'Ebonyi'),
    ('Edo', 'Edo'),
    ('Ekiti', 'Ekiti'),
    ('Enugu', 'Enugu'),
    ('Gombe', 'Gombe'),
    ('Imo', 'Imo'),
    ('Jigawa', 'Jigawa'),
    ('Kaduna', 'Kaduna'),
    ('Kano', 'Kano'),
    ('Katsina', 'Katsina'),
    ('Kebbi', 'Kebbi'),
    ('Kogi', 'Kogi'),
    ('Kwara', 'Kwara'),
    ('Lagos', 'Lagos'),
    ('Nasarawa', 'Nasarawa'),
    ('Niger', 'Niger'),
    ('Ogun', 'Ogun'),
    ('Ondo', 'Ondo'),
    ('Osun', 'Osun'),
    ('Oyo', 'Oyo'),
    ('Plateau', 'Plateau'),
    ('Rivers', 'Rivers'),
    ('Sokoto', 'Sokoto'),
    ('Taraba', 'Taraba'),
    ('Yobe', 'Yobe'),
    ('Zamfara', 'Zamfara'),
]
