# Generated by Django 3.2 on 2023-11-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Property', '0001_initial'),
        ('Tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('date_reported', models.DateTimeField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('date_completed', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('assigned_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MaintenanceRequest.vendor')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenant.tenant')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
