# Generated by Django 3.2 on 2023-11-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization', '0002_auto_20231113_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_Landlord',
            field=models.BooleanField(default=False),
        ),
    ]
