# Generated by Django 3.2 on 2023-12-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization', '0003_customuser_is_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
