# Generated by Django 3.2 on 2023-12-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization', '0004_auto_20231210_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_Subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
