# Generated by Django 3.2 on 2023-12-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization', '0005_customuser_is_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=True, max_length=30, null=True, unique=True),
        ),
    ]
