# Generated by Django 3.2 on 2023-12-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization', '0008_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
