# Generated by Django 3.2 on 2023-11-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0001_initial'),
        ('Property', '0002_auto_20231108_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tenants',
            field=models.ManyToManyField(blank=True, null=True, to='Tenant.Tenant'),
        ),
    ]
