# Generated by Django 3.2 on 2023-11-13 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Property', '0006_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Authorization.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Authorization.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='tenants',
            field=models.ManyToManyField(blank=True, to='Tenant.Tenant'),
        ),
    ]
