# Generated by Django 3.2 on 2023-11-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0008_property_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_estate',
            field=models.BooleanField(default=False),
        ),
    ]
